[control_plane]
k8scp01.vollminlab.com
k8scp02.vollminlab.com
k8scp03.vollminlab.com

[workers]
k8sworker01.vollminlab.com
k8sworker02.vollminlab.com
k8sworker03.vollminlab.com
k8sworker04.vollminlab.com
k8sworker05.vollminlab.com
k8sworker06.vollminlab.com

[k8s:children]
control_plane
workers

[k8s:vars]
ansible_user=vollmin
